/*
document.getElementById('searchregion-searchpage').onchange = function(){
    var regionSelected = document.getElementById('searchregion-searchpage').value;
    var defaultCitySelection = document.getElementById('defualtCitySelect');
    var blekingeSelection = document.getElementById('blekingeCitySelect');
    var dalarnaSelection = document.getElementById('dalarnaCitySelect');
    var gotlandSelection = document.getElementById('gotlandCitySelect');
    var gävleborgSelection = document.getElementById('gävleborgCitySelect');
    var hallandSelection = document.getElementById('hallandCitySelect');
    var jämtlandSelection = document.getElementById('jämtlandCitySelect');
    var jönköpingSelection = document.getElementById('jönköpingCitySelect');
    var kalmarSelection = document.getElementById('kalmarCitySelect');
    var kronobergSelection = document.getElementById('kronobergCitySelect');
    var norrbottenSelection = document.getElementById('norrbottenCitySelect');
    var skåneSelection = document.getElementById('skåneCitySelect');
    var stockholmSelection = document.getElementById('stockholmCitySelect');
    var södermanlandSelection = document.getElementById('södermanlandCitySelect');
    var uppsalaSelection = document.getElementById('uppsalaCitySelect');
    var värmlandSelection = document.getElementById('värmlandCitySelect');
    var västerbottenSelection = document.getElementById('västerbottenCitySelect');
    var västernorrlandSelection = document.getElementById('västernorrlandCitySelect');
    var västmanlandSelection = document.getElementById('västmanlandCitySelect');
    var västraGötalandSelection = document.getElementById('västraGötalandCitySelect');
    var örebroSelection = document.getElementById('örebroCitySelect');
    var östergötlandSelection = document.getElementById('östergötlandCitySelect');

    if(regionSelected === 'Hela Sverige'){
        localStorage.setItem("regionSelected", "Hela Sverige");
        location.reload();
    }
    else if(regionSelected === 'Blekinge'){
        defaultCitySelection.style.display = "none";
        blekingeSelection.style.display = "block";
        dalarnaSelection.style.display = "none";
        gotlandSelection.style.display = "none";
        gävleborgSelection.style.display = "none";
        hallandSelection.style.display = "none";
        jämtlandSelection.style.display = "none";
        jönköpingSelection.style.display = "none";
        kalmarSelection.style.display = "none";
        kronobergSelection.style.display = "none";
        norrbottenSelection.style.display = "none";
        skåneSelection.style.display = "none";
        stockholmSelection.style.display = "none";
        södermanlandSelection.style.display = "none";
        uppsalaSelection.style.display = "none";
        värmlandSelection.style.display = "none";
        västerbottenSelection.style.display = "none";
        västernorrlandSelection.style.display = "none";
        västmanlandSelection.style.display = "none";
        västraGötalandSelection.style.display = "none";
        örebroSelection.style.display = "none";
        östergötlandSelection.style.display = "none";
        localStorage.setItem("regionSelected", `${regionSelected}`);
        location.reload();
    }
    else if(regionSelected === 'Dalarna'){
        defaultCitySelection.style.display = "none";
        blekingeSelection.style.display = "none";
        dalarnaSelection.style.display = "block";
        gotlandSelection.style.display = "none";
        gävleborgSelection.style.display = "none";
        hallandSelection.style.display = "none";
        jämtlandSelection.style.display = "none";
        jönköpingSelection.style.display = "none";
        kalmarSelection.style.display = "none";
        kronobergSelection.style.display = "none";
        norrbottenSelection.style.display = "none";
        skåneSelection.style.display = "none";
        stockholmSelection.style.display = "none";
        södermanlandSelection.style.display = "none";
        uppsalaSelection.style.display = "none";
        värmlandSelection.style.display = "none";
        västerbottenSelection.style.display = "none";
        västernorrlandSelection.style.display = "none";
        västmanlandSelection.style.display = "none";
        västraGötalandSelection.style.display = "none";
        örebroSelection.style.display = "none";
        östergötlandSelection.style.display = "none";
        localStorage.setItem("regionSelected", `${regionSelected}`);
        location.reload();
    }
    else if(regionSelected === 'Gotland'){
        defaultCitySelection.style.display = "none";
        blekingeSelection.style.display = "none";
        dalarnaSelection.style.display = "none";
        gotlandSelection.style.display = "block";
        gävleborgSelection.style.display = "none";
        hallandSelection.style.display = "none";
        jämtlandSelection.style.display = "none";
        jönköpingSelection.style.display = "none";
        kalmarSelection.style.display = "none";
        kronobergSelection.style.display = "none";
        norrbottenSelection.style.display = "none";
        skåneSelection.style.display = "none";
        stockholmSelection.style.display = "none";
        södermanlandSelection.style.display = "none";
        uppsalaSelection.style.display = "none";
        värmlandSelection.style.display = "none";
        västerbottenSelection.style.display = "none";
        västernorrlandSelection.style.display = "none";
        västmanlandSelection.style.display = "none";
        västraGötalandSelection.style.display = "none";
        örebroSelection.style.display = "none";
        östergötlandSelection.style.display = "none";
        localStorage.setItem("regionSelected", `${regionSelected}`);
        location.reload();
    }
    else if(regionSelected === 'Gävleborg'){
        defaultCitySelection.style.display = "none";
        blekingeSelection.style.display = "none";
        dalarnaSelection.style.display = "none";
        gotlandSelection.style.display = "none";
        gävleborgSelection.style.display = "block";
        hallandSelection.style.display = "none";
        jämtlandSelection.style.display = "none";
        jönköpingSelection.style.display = "none";
        kalmarSelection.style.display = "none";
        kronobergSelection.style.display = "none";
        norrbottenSelection.style.display = "none";
        skåneSelection.style.display = "none";
        stockholmSelection.style.display = "none";
        södermanlandSelection.style.display = "none";
        uppsalaSelection.style.display = "none";
        värmlandSelection.style.display = "none";
        västerbottenSelection.style.display = "none";
        västernorrlandSelection.style.display = "none";
        västmanlandSelection.style.display = "none";
        västraGötalandSelection.style.display = "none";
        örebroSelection.style.display = "none";
        östergötlandSelection.style.display = "none"; 
        localStorage.setItem("regionSelected", `${regionSelected}`);
        location.reload();
    }
    else if(regionSelected === 'Halland'){
        defaultCitySelection.style.display = "none";
        blekingeSelection.style.display = "none";
        dalarnaSelection.style.display = "none";
        gotlandSelection.style.display = "none";
        gävleborgSelection.style.display = "none";
        hallandSelection.style.display = "block";
        jämtlandSelection.style.display = "none";
        jönköpingSelection.style.display = "none";
        kalmarSelection.style.display = "none";
        kronobergSelection.style.display = "none";
        norrbottenSelection.style.display = "none";
        skåneSelection.style.display = "none";
        stockholmSelection.style.display = "none";
        södermanlandSelection.style.display = "none";
        uppsalaSelection.style.display = "none";
        värmlandSelection.style.display = "none";
        västerbottenSelection.style.display = "none";
        västernorrlandSelection.style.display = "none";
        västmanlandSelection.style.display = "none";
        västraGötalandSelection.style.display = "none";
        örebroSelection.style.display = "none";
        östergötlandSelection.style.display = "none";
        localStorage.setItem("regionSelected", `${regionSelected}`);
        location.reload();
    }
    else if(regionSelected === 'Jämtland'){
        defaultCitySelection.style.display = "none";
        blekingeSelection.style.display = "none";
        dalarnaSelection.style.display = "none";
        gotlandSelection.style.display = "none";
        gävleborgSelection.style.display = "none";
        hallandSelection.style.display = "none";
        jämtlandSelection.style.display = "block";
        jönköpingSelection.style.display = "none";
        kalmarSelection.style.display = "none";
        kronobergSelection.style.display = "none";
        norrbottenSelection.style.display = "none";
        skåneSelection.style.display = "none";
        stockholmSelection.style.display = "none";
        södermanlandSelection.style.display = "none";
        uppsalaSelection.style.display = "none";
        värmlandSelection.style.display = "none";
        västerbottenSelection.style.display = "none";
        västernorrlandSelection.style.display = "none";
        västmanlandSelection.style.display = "none";
        västraGötalandSelection.style.display = "none";
        örebroSelection.style.display = "none";
        östergötlandSelection.style.display = "none";
        localStorage.setItem("regionSelected", `${regionSelected}`);
        location.reload();
    }
    else if(regionSelected === 'Jönköping'){
        defaultCitySelection.style.display = "none";
        blekingeSelection.style.display = "none";
        dalarnaSelection.style.display = "none";
        gotlandSelection.style.display = "none";
        gävleborgSelection.style.display = "none";
        hallandSelection.style.display = "none";
        jämtlandSelection.style.display = "none";
        jönköpingSelection.style.display = "block";
        kalmarSelection.style.display = "none";
        kronobergSelection.style.display = "none";
        norrbottenSelection.style.display = "none";
        skåneSelection.style.display = "none";
        stockholmSelection.style.display = "none";
        södermanlandSelection.style.display = "none";
        uppsalaSelection.style.display = "none";
        värmlandSelection.style.display = "none";
        västerbottenSelection.style.display = "none";
        västernorrlandSelection.style.display = "none";
        västmanlandSelection.style.display = "none";
        västraGötalandSelection.style.display = "none";
        örebroSelection.style.display = "none";
        östergötlandSelection.style.display = "none";
        localStorage.setItem("regionSelected", `${regionSelected}`);
        location.reload();
    }
    else if(regionSelected === 'Kalmar'){
        defaultCitySelection.style.display = "none";
        blekingeSelection.style.display = "none";
        dalarnaSelection.style.display = "none";
        gotlandSelection.style.display = "none";
        gävleborgSelection.style.display = "none";
        hallandSelection.style.display = "none";
        jämtlandSelection.style.display = "none";
        jönköpingSelection.style.display = "none";
        kalmarSelection.style.display = "block";
        kronobergSelection.style.display = "none";
        norrbottenSelection.style.display = "none";
        skåneSelection.style.display = "none";
        stockholmSelection.style.display = "none";
        södermanlandSelection.style.display = "none";
        uppsalaSelection.style.display = "none";
        värmlandSelection.style.display = "none";
        västerbottenSelection.style.display = "none";
        västernorrlandSelection.style.display = "none";
        västmanlandSelection.style.display = "none";
        västraGötalandSelection.style.display = "none";
        örebroSelection.style.display = "none";
        östergötlandSelection.style.display = "none";
        localStorage.setItem("regionSelected", `${regionSelected}`);
        location.reload();
    }
    else if(regionSelected === 'Kronoberg'){
        defaultCitySelection.style.display = "none";
        blekingeSelection.style.display = "none";
        dalarnaSelection.style.display = "none";
        gotlandSelection.style.display = "none";
        gävleborgSelection.style.display = "none";
        hallandSelection.style.display = "none";
        jämtlandSelection.style.display = "none";
        jönköpingSelection.style.display = "none";
        kalmarSelection.style.display = "none";
        kronobergSelection.style.display = "block";
        norrbottenSelection.style.display = "none";
        skåneSelection.style.display = "none";
        stockholmSelection.style.display = "none";
        södermanlandSelection.style.display = "none";
        uppsalaSelection.style.display = "none";
        värmlandSelection.style.display = "none";
        västerbottenSelection.style.display = "none";
        västernorrlandSelection.style.display = "none";
        västmanlandSelection.style.display = "none";
        västraGötalandSelection.style.display = "none";
        örebroSelection.style.display = "none";
        östergötlandSelection.style.display = "none";
        localStorage.setItem("regionSelected", `${regionSelected}`);
        location.reload();
    }
    else if(regionSelected === 'Norrbotten'){
        defaultCitySelection.style.display = "none";
        blekingeSelection.style.display = "none";
        dalarnaSelection.style.display = "none";
        gotlandSelection.style.display = "none";
        gävleborgSelection.style.display = "none";
        hallandSelection.style.display = "none";
        jämtlandSelection.style.display = "none";
        jönköpingSelection.style.display = "none";
        kalmarSelection.style.display = "none";
        kronobergSelection.style.display = "none";
        norrbottenSelection.style.display = "block";
        skåneSelection.style.display = "none";
        stockholmSelection.style.display = "none";
        södermanlandSelection.style.display = "none";
        uppsalaSelection.style.display = "none";
        värmlandSelection.style.display = "none";
        västerbottenSelection.style.display = "none";
        västernorrlandSelection.style.display = "none";
        västmanlandSelection.style.display = "none";
        västraGötalandSelection.style.display = "none";
        örebroSelection.style.display = "none";
        östergötlandSelection.style.display = "none";
        localStorage.setItem("regionSelected", `${regionSelected}`);
        location.reload();
    }
    else if(regionSelected === 'Skåne'){
        defaultCitySelection.style.display = "none";
        blekingeSelection.style.display = "none";
        dalarnaSelection.style.display = "none";
        gotlandSelection.style.display = "none";
        gävleborgSelection.style.display = "none";
        hallandSelection.style.display = "none";
        jämtlandSelection.style.display = "none";
        jönköpingSelection.style.display = "none";
        kalmarSelection.style.display = "none";
        kronobergSelection.style.display = "none";
        norrbottenSelection.style.display = "none";
        skåneSelection.style.display = "block";
        stockholmSelection.style.display = "none";
        södermanlandSelection.style.display = "none";
        uppsalaSelection.style.display = "none";
        värmlandSelection.style.display = "none";
        västerbottenSelection.style.display = "none";
        västernorrlandSelection.style.display = "none";
        västmanlandSelection.style.display = "none";
        västraGötalandSelection.style.display = "none";
        örebroSelection.style.display = "none";
        östergötlandSelection.style.display = "none";
        localStorage.setItem("regionSelected", `${regionSelected}`);
        location.reload();
    }
    else if(regionSelected === 'Stockholm'){
        defaultCitySelection.style.display = "none";
        blekingeSelection.style.display = "none";
        dalarnaSelection.style.display = "none";
        gotlandSelection.style.display = "none";
        gävleborgSelection.style.display = "none";
        hallandSelection.style.display = "none";
        jämtlandSelection.style.display = "none";
        jönköpingSelection.style.display = "none";
        kalmarSelection.style.display = "none";
        kronobergSelection.style.display = "none";
        norrbottenSelection.style.display = "none";
        skåneSelection.style.display = "none";
        stockholmSelection.style.display = "block";
        södermanlandSelection.style.display = "none";
        uppsalaSelection.style.display = "none";
        värmlandSelection.style.display = "none";
        västerbottenSelection.style.display = "none";
        västernorrlandSelection.style.display = "none";
        västmanlandSelection.style.display = "none";
        västraGötalandSelection.style.display = "none";
        örebroSelection.style.display = "none";
        östergötlandSelection.style.display = "none";
        localStorage.setItem("regionSelected", `${regionSelected}`);
        location.reload();
    }
    else if(regionSelected === 'Sörmland'){
        defaultCitySelection.style.display = "none";
        blekingeSelection.style.display = "none";
        dalarnaSelection.style.display = "none";
        gotlandSelection.style.display = "none";
        gävleborgSelection.style.display = "none";
        hallandSelection.style.display = "none";
        jämtlandSelection.style.display = "none";
        jönköpingSelection.style.display = "none";
        kalmarSelection.style.display = "none";
        kronobergSelection.style.display = "none";
        norrbottenSelection.style.display = "none";
        skåneSelection.style.display = "none";
        stockholmSelection.style.display = "none";
        södermanlandSelection.style.display = "block";
        uppsalaSelection.style.display = "none";
        värmlandSelection.style.display = "none";
        västerbottenSelection.style.display = "none";
        västernorrlandSelection.style.display = "none";
        västmanlandSelection.style.display = "none";
        västraGötalandSelection.style.display = "none";
        örebroSelection.style.display = "none";
        östergötlandSelection.style.display = "none";
        localStorage.setItem("regionSelected", `${regionSelected}`);
        location.reload();
    }
    else if(regionSelected === 'Uppsala'){
        defaultCitySelection.style.display = "none";
        blekingeSelection.style.display = "none";
        dalarnaSelection.style.display = "none";
        gotlandSelection.style.display = "none";
        gävleborgSelection.style.display = "none";
        hallandSelection.style.display = "none";
        jämtlandSelection.style.display = "none";
        jönköpingSelection.style.display = "none";
        kalmarSelection.style.display = "none";
        kronobergSelection.style.display = "none";
        norrbottenSelection.style.display = "none";
        skåneSelection.style.display = "none";
        stockholmSelection.style.display = "none";
        södermanlandSelection.style.display = "none";
        uppsalaSelection.style.display = "block";
        värmlandSelection.style.display = "none";
        västerbottenSelection.style.display = "none";
        västernorrlandSelection.style.display = "none";
        västmanlandSelection.style.display = "none";
        västraGötalandSelection.style.display = "none";
        örebroSelection.style.display = "none";
        östergötlandSelection.style.display = "none";
        localStorage.setItem("regionSelected", `${regionSelected}`);
        location.reload();
    }
    else if(regionSelected === 'Värmland'){
        defaultCitySelection.style.display = "none";
        blekingeSelection.style.display = "none";
        dalarnaSelection.style.display = "none";
        gotlandSelection.style.display = "none";
        gävleborgSelection.style.display = "none";
        hallandSelection.style.display = "none";
        jämtlandSelection.style.display = "none";
        jönköpingSelection.style.display = "none";
        kalmarSelection.style.display = "none";
        kronobergSelection.style.display = "none";
        norrbottenSelection.style.display = "none";
        skåneSelection.style.display = "none";
        stockholmSelection.style.display = "none";
        södermanlandSelection.style.display = "none";
        uppsalaSelection.style.display = "none";
        värmlandSelection.style.display = "block";
        västerbottenSelection.style.display = "none";
        västernorrlandSelection.style.display = "none";
        västmanlandSelection.style.display = "none";
        västraGötalandSelection.style.display = "none";
        örebroSelection.style.display = "none";
        östergötlandSelection.style.display = "none";
        localStorage.setItem("regionSelected", `${regionSelected}`);
        location.reload();
    }
    else if(regionSelected === 'Västerbotten'){
        defaultCitySelection.style.display = "none";
        blekingeSelection.style.display = "none";
        dalarnaSelection.style.display = "none";
        gotlandSelection.style.display = "none";
        gävleborgSelection.style.display = "none";
        hallandSelection.style.display = "none";
        jämtlandSelection.style.display = "none";
        jönköpingSelection.style.display = "none";
        kalmarSelection.style.display = "none";
        kronobergSelection.style.display = "none";
        norrbottenSelection.style.display = "none";
        skåneSelection.style.display = "none";
        stockholmSelection.style.display = "none";
        södermanlandSelection.style.display = "none";
        uppsalaSelection.style.display = "none";
        värmlandSelection.style.display = "none";
        västerbottenSelection.style.display = "block";
        västernorrlandSelection.style.display = "none";
        västmanlandSelection.style.display = "none";
        västraGötalandSelection.style.display = "none";
        örebroSelection.style.display = "none";
        östergötlandSelection.style.display = "none";
        localStorage.setItem("regionSelected", `${regionSelected}`);
        location.reload();
    }
    else if(regionSelected === 'Västernorrland'){
        defaultCitySelection.style.display = "none";
        blekingeSelection.style.display = "none";
        dalarnaSelection.style.display = "none";
        gotlandSelection.style.display = "none";
        gävleborgSelection.style.display = "none";
        hallandSelection.style.display = "none";
        jämtlandSelection.style.display = "none";
        jönköpingSelection.style.display = "none";
        kalmarSelection.style.display = "none";
        kronobergSelection.style.display = "none";
        norrbottenSelection.style.display = "none";
        skåneSelection.style.display = "none";
        stockholmSelection.style.display = "none";
        södermanlandSelection.style.display = "none";
        uppsalaSelection.style.display = "none";
        värmlandSelection.style.display = "none";
        västerbottenSelection.style.display = "none";
        västernorrlandSelection.style.display = "block";
        västmanlandSelection.style.display = "none";
        västraGötalandSelection.style.display = "none";
        örebroSelection.style.display = "none";
        östergötlandSelection.style.display = "none";
        localStorage.setItem("regionSelected", `${regionSelected}`);
        location.reload();
    }
    else if(regionSelected === 'Västmanland'){
        defaultCitySelection.style.display = "none";
        blekingeSelection.style.display = "none";
        dalarnaSelection.style.display = "none";
        gotlandSelection.style.display = "none";
        gävleborgSelection.style.display = "none";
        hallandSelection.style.display = "none";
        jämtlandSelection.style.display = "none";
        jönköpingSelection.style.display = "none";
        kalmarSelection.style.display = "none";
        kronobergSelection.style.display = "none";
        norrbottenSelection.style.display = "none";
        skåneSelection.style.display = "none";
        stockholmSelection.style.display = "none";
        södermanlandSelection.style.display = "none";
        uppsalaSelection.style.display = "none";
        värmlandSelection.style.display = "none";
        västerbottenSelection.style.display = "none";
        västernorrlandSelection.style.display = "none";
        västmanlandSelection.style.display = "block";
        västraGötalandSelection.style.display = "none";
        örebroSelection.style.display = "none";
        östergötlandSelection.style.display = "none";
        localStorage.setItem("regionSelected", `${regionSelected}`);
        location.reload();
    }
    else if(regionSelected === 'Västra Götaland'){
        defaultCitySelection.style.display = "none";
        blekingeSelection.style.display = "none";
        dalarnaSelection.style.display = "none";
        gotlandSelection.style.display = "none";
        gävleborgSelection.style.display = "none";
        hallandSelection.style.display = "none";
        jämtlandSelection.style.display = "none";
        jönköpingSelection.style.display = "none";
        kalmarSelection.style.display = "none";
        kronobergSelection.style.display = "none";
        norrbottenSelection.style.display = "none";
        skåneSelection.style.display = "none";
        stockholmSelection.style.display = "none";
        södermanlandSelection.style.display = "none";
        uppsalaSelection.style.display = "none";
        värmlandSelection.style.display = "none";
        västerbottenSelection.style.display = "none";
        västernorrlandSelection.style.display = "none";
        västmanlandSelection.style.display = "none";
        västraGötalandSelection.style.display = "block";
        örebroSelection.style.display = "none";
        östergötlandSelection.style.display = "none";
        localStorage.setItem("regionSelected", `${regionSelected}`);
        location.reload();
    }
    else if(regionSelected === 'Örebro'){
        defaultCitySelection.style.display = "none";
        blekingeSelection.style.display = "none";
        dalarnaSelection.style.display = "none";
        gotlandSelection.style.display = "none";
        gävleborgSelection.style.display = "none";
        hallandSelection.style.display = "none";
        jämtlandSelection.style.display = "none";
        jönköpingSelection.style.display = "none";
        kalmarSelection.style.display = "none";
        kronobergSelection.style.display = "none";
        norrbottenSelection.style.display = "none";
        skåneSelection.style.display = "none";
        stockholmSelection.style.display = "none";
        södermanlandSelection.style.display = "none";
        uppsalaSelection.style.display = "none";
        värmlandSelection.style.display = "none";
        västerbottenSelection.style.display = "none";
        västernorrlandSelection.style.display = "none";
        västmanlandSelection.style.display = "none";
        västraGötalandSelection.style.display = "none";
        örebroSelection.style.display = "block";
        östergötlandSelection.style.display = "none";
        localStorage.setItem("regionSelected", `${regionSelected}`);
        location.reload();
    }
    else if(regionSelected === 'Östergötland'){
        defaultCitySelection.style.display = "none";
        blekingeSelection.style.display = "none";
        dalarnaSelection.style.display = "none";
        gotlandSelection.style.display = "none";
        gävleborgSelection.style.display = "none";
        hallandSelection.style.display = "none";
        jämtlandSelection.style.display = "none";
        jönköpingSelection.style.display = "none";
        kalmarSelection.style.display = "none";
        kronobergSelection.style.display = "none";
        norrbottenSelection.style.display = "none";
        skåneSelection.style.display = "none";
        stockholmSelection.style.display = "none";
        södermanlandSelection.style.display = "none";
        uppsalaSelection.style.display = "none";
        värmlandSelection.style.display = "none";
        västerbottenSelection.style.display = "none";
        västernorrlandSelection.style.display = "none";
        västmanlandSelection.style.display = "none";
        västraGötalandSelection.style.display = "none";
        örebroSelection.style.display = "none";
        östergötlandSelection.style.display = "block";
        localStorage.setItem("regionSelected", `${regionSelected}`);
        location.reload();
    }
}
*/